---
title: "Schedule"
---

| Week | Date | Topic | Slides | Lab | Assignment |
|:--:|:---:|:-----------------------|:--:|:--:|:--:|
| 1 | 8/26 | Introduction to Data Science & R | [Slides](slides/week01.qmd) | [Lab](labs/lab1.qmd) |  |
| 2 | 9/2 | Version Control & Reproducible Research | [Slides](slides/week02.qmd) | [Lab](labs/lab2.qmd) |  |
| 3 | 9/9 | Exploratory Data Analysis | [Slides](slides/week03.qmd) | [Lab](labs/lab3.qmd) | [HW1](assignments/hw1.qmd) |
| 4 | 9/16 | Data Visualization	 | [Slides](slides/week04.qmd) | [Lab](labs/lab4.qmd) |  |
| 5 | 9/23 | Data Cleaning and Wrangling	 | [Slides](slides/week05.qmd) | [Lab](labs/lab5.qmd) | [HW2](assignments/hw2.qmd) |
| 6 | 9/30 | Text Mining & Sentiment Analysis	 | [Slides](slides/week06.qmd) | [Lab](labs/lab6.qmd) |  |
|   | 10/7 | Review (NO LAB - FALL RECESS)	 |  |  | [Midterm](assignments/midterm.qmd) |
| 7 | 10/14 | Scraping, APIs, & Regular Expressions	 | [Slides](slides/week07.qmd) | [Lab](labs/lab7.qmd) |  |
| 8 | 10/21 | Efficiency & High Performance Computing | [Slides](slides/week08.qmd) | [Lab](labs/lab8.qmd) | [HW3](assignments/hw3.qmd) |
| 9 | 10/28 | SQL & Managing Big Data	 | [Slides](slides/week09.qmd) | [Lab](labs/lab9.qmd) |  |
| 10 | 11/4 | Interactive Visualization | [Slides](slides/week10.qmd) | [Lab](labs/lab10.qmd) | [HW4](assignments/hw4.qmd) |
| 11 | 11/11 | Building a Website (NO CLASS WED - VETERAN'S DAY) | [Slides](slides/week11.qmd) | [Lab](https://quarto.org/docs/publishing/github-pages.html) |  |
| 12 | 11/18 | Unsupervised Learning OR Interactive Visualization II |  |  |  |
|    | 11/25 | NO CLASS - THANKSGIVING	 |  |  | [Final](assignments/final.qmd) |
| 13 | 12/2 | Nonparametric Statistics	 |  |  |  |

